In [1]:
from regression import *
from gapminder_explorer import load_and_prepare_many, load_many

In [8]:
# papers = load_and_prepare_many([
#         r"..\..\..\..\review_output\gapminder\manual.parquet",
#         r"..\..\..\..\review_output\gapminder\20250731_fixed.parquet",
#     ])
papers = load_many([
        r"..\..\..\..\review_output\gapminder\2025117_manual.parquet",
        r"..\..\..\..\review_output\gapminder\2025117_auto.parquet",
    ])
state = show_regression_dashboard(
    papers,
    default_time="Year",
)

VBox(children=(HBox(children=(VBox(children=(Dropdown(description='Time', index=3, options=('n_modalities', 'n…

In [3]:
from regression import compute_trends_by_category
relative = False

In [4]:
compute_trends_by_category(
    papers, category_col="Imaging Method", time_col="Year",
    start=2014, end=2023, y_measure="count", alpha=0.05, relative=relative
)

,Imaging Method,slope,intercept,r2,n,slope_std_err,t_stat,p_value,slope_ci_low,slope_ci_high,significant
0,Non-specialized Camera,27.187879,-54741.933333,0.928512,10,2.667193,10.193441,0.000007,21.037320,33.338438,True
1,Camera Trap,5.551515,-11183.933333,0.872065,10,0.751772,7.384576,0.000077,3.817926,7.285104,True
2,Unmanned aerial vehicle (UAV; e.g. drone),2.400000,-4830.800000,0.851003,10,0.355050,6.759609,0.000144,1.581253,3.218747,True
3,Depth Sensor / Lidar,2.000000,-4029.000000,0.753425,10,0.404520,4.944132,0.001129,1.067175,2.932825,True
4,Other,1.909091,-3844.600000,0.892496,10,0.234256,8.149581,0.000038,1.368895,2.449287,True
5,Remotely operated underwater vehicle (ROV),1.233333,-2484.655556,0.785277,9,0.243758,5.059662,0.001464,0.656937,1.809730,True
6,Satellite,0.746774,-1503.209677,0.831145,9,0.127221,5.869903,0.000618,0.445945,1.047604,True
7,"Crewed aerial vehicle (CAV; e.g. plane, helico...",0.670833,-1350.300000,0.707451,9,0.163049,4.114317,0.004491,0.285285,1.056382,True
8,Ground Robot,0.571429,-1151.571429,0.592593,7,0.211891,2.696799,0.042948,0.026744,1.116113,True
9,Autonomous Underwater Vehicle (AUV),0.375806,-753.822581,0.295821,9,0.219151,1.714832,0.130092,-0.142402,0.894015,False
10,Animal-mounted Camera,-0.115460,235.166341,0.296180,8,0.072662,-1.588994,0.163162,-0.293258,0.062338,False

In [5]:
compute_trends_by_category(
    papers, category_col="CV Tasks", time_col="Year",
    start=2014, end=2023, y_measure="count", alpha=0.05, relative=relative
)

,CV Tasks,slope,intercept,r2,n,slope_std_err,t_stat,p_value,slope_ci_low,slope_ci_high,significant
0,Classification,2.293333e+01,-46189.133333,0.909191,10,2.562472e+00,8.949691,0.000019,1.702426e+01,2.884240e+01,True
1,Detection,1.965455e+01,-39567.600000,0.934959,10,1.832805e+00,10.723753,0.000005,1.542809e+01,2.388100e+01,True
2,Tracking,8.242424e+00,-16582.933333,0.920578,10,8.559520e-01,9.629540,0.000011,6.268595e+00,1.021625e+01,True
3,Activity Recognition,8.236364e+00,-16571.800000,0.854170,10,1.203210e+00,6.845327,0.000132,5.461757e+00,1.101097e+01,True
4,Pose Estimation,7.133333e+00,-14365.933333,0.865542,10,9.940225e-01,7.176229,0.000095,4.841113e+00,9.425553e+00,True
5,Segmentation,5.854545e+00,-11768.800000,0.906794,10,6.636156e-01,8.822194,0.000021,4.324245e+00,7.384846e+00,True
6,Reconstruction,5.084848e+00,-10238.866667,0.775417,10,9.675070e-01,5.255619,0.000769,2.853773e+00,7.315924e+00,True
7,Identification,3.654545e+00,-7354.600000,0.876637,10,4.846969e-01,7.539857,0.000067,2.536832e+00,4.772259e+00,True
8,Synthesis,3.454545e+00,-6962.000000,0.732549,10,7.379892e-01,4.681024,0.001580,1.752739e+00,5.156352e+00,True
9,Unknown,1.030303e-01,-205.866667,0.067888,10,1.349761e-01,0.763323,0.467182,-2.082252e-01,4.142858e-01,False
10,Shape Estimation,-4.310361e-17,1.000000,0.000000,2,7.850462e-17,-0.549058,0.680341,-1.040599e-15,9.543922e-16,False

In [6]:
compute_trends_by_category(
    papers, category_col="ParentHabitat", time_col="Year",
    start=2014, end=2023, y_measure="count", alpha=0.05, relative=relative
)

,ParentHabitat,slope,intercept,r2,n,slope_std_err,t_stat,p_value,slope_ci_low,slope_ci_high,significant
0,Artificial Terrestrial,16.896970,-34030.133333,0.885956,10,2.143356,7.883416,0.000049,11.954381,21.839558,True
1,Unknown / Other,16.672727,-33578.800000,0.924698,10,1.682154,9.911535,0.000009,12.793673,20.551781,True
2,Grassland,9.915152,-19966.333333,0.931567,10,0.950124,10.435635,0.000006,7.724161,12.106142,True
3,Forest,9.600000,-19335.000000,0.933549,10,0.905539,10.601427,0.000005,7.511824,11.688176,True
4,Marine,9.266667,-18649.466667,0.891328,10,1.143979,8.100385,0.000040,6.628647,11.904686,True
5,Artificial Aquatic,7.296970,-14687.333333,0.842432,10,1.115744,6.540002,0.000180,4.724059,9.869881,True
6,Shrubland,7.115152,-14325.733333,0.929868,10,0.690856,10.299038,0.000007,5.522035,8.708268,True
7,Wetlands (inland),6.193939,-12470.066667,0.916253,10,0.662064,9.355499,0.000014,4.667217,7.720662,True
8,"Rocky areas (e.g. inland cliffs, mountain peaks)",4.600000,-9266.000000,0.828563,10,0.739779,6.218075,0.000254,2.894067,6.305933,True
9,Savanna,4.454545,-8968.400000,0.874070,10,0.597792,7.451664,0.000073,3.076034,5.833056,True
10,Desert,3.806061,-7665.133333,0.914806,10,0.410648,9.268426,0.000015,2.859105,4.753017,True
11,Cave and subterranean habitats (non-aquatic),1.781818,-3588.200000,0.692197,10,0.420088,4.241537,0.002832,0.813094,2.750543,True

In [7]:
allowed = ["COCO", "iNaturlist", "Snapshot"]
papers2 = papers[papers["Dataset"].apply(lambda lst: any(x in allowed for x in lst))]

compute_trends_by_category(
    papers2, category_col="Dataset", time_col="Year",
    start=2014, end=2023, y_measure="count", alpha=0.05, relative=relative
)

,Dataset,slope,intercept,r2,n,slope_std_err,t_stat,p_value,slope_ci_low,slope_ci_high,significant
0,COCO,1.257143e+00,-2535.72381,0.669124,6,4.420115e-01,2.844141e+00,4.667159e-02,2.992224e-02,2.484363e+00,True
1,ImageNet-LT,5.000000e-01,-1009.50000,1.000000,2,4.099037e-13,1.219799e+12,5.219056e-13,5.000000e-01,5.000000e-01,True
2,ImageNet,5.428571e-01,-1094.67619,0.476044,6,2.847603e-01,1.906365e+00,1.292864e-01,-2.477642e-01,1.333479e+00,False
3,Snapshot Serengeti,5.390274e-17,1.00000,0.000000,2,1.170278e-16,4.605978e-01,7.252145e-01,-1.433076e-15,1.540882e-15,False
4,Animal Pose dataset,-1.618204e-17,1.00000,0.000000,2,1.110223e-16,-1.457548e-01,9.078584e-01,-1.426854e-15,1.394490e-15,False
...,...,...,...,...,...,...,...,...,...,...,...
61,YFCC100M,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,False
62,iNat2017,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,False
63,iNaturalist,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,False
64,rfishbase,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,False
65,sharkPulse,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,False